# Generated by Django 4.1.1 on 2022-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210730_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('Liberary', 'Liberary'), ('Bus', 'Bus'), ('None', 'None'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('vii', 'vii'), ('iv', 'iv'), ('viii', 'viii'), ('x', 'x'), ('ii', 'ii'), ('iii', 'iii'), ('ix', 'ix'), ('i', 'i'), ('vi', 'vi'), ('v', 'v')], max_length=50, null=True),
        ),
    ]
